services:
  nginx:
    image: nginx:latest
    container_name: dossierfacile_reverse_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.nginx/certs:/etc/nginx/certs
    restart: unless-stopped
    networks:
      - dossierfacile_network
  postgres:
    image: postgres:12
    container_name: dossierfacile_postgres_db
    hostname: localhost
    environment:
      POSTGRES_USER: dossierfacile
      POSTGRES_PASSWORD: your_very_secure_password
      POSTGRES_DB: dossierfacile
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U dossierfacile" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dossierfacile_network

  rabbitmq:
    container_name: 'dossierfacile_rabbit'
    image: 'rabbitmq:3-management'
    hostname: localhost
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ./.rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    restart: unless-stopped
    networks:
      - dossierfacile_network

volumes:
  postgres_data:
    driver: local

networks:
  dossierfacile_network:
    driver: bridge